# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    set ::env(RT_TMP) "./.Xil/Vivado-8072-804-064/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      D:/CPU/CPU.srcs/sources_1/new/divider.v
      D:/CPU/CPU.srcs/sources_1/new/display.v
      D:/CPU/CPU.srcs/sources_1/new/Register.v
      D:/CPU/CPU.srcs/sources_1/new/mux.v
      D:/CPU/CPU.srcs/sources_1/new/Extender.v
      D:/CPU/CPU.srcs/sources_1/new/ram.v
      D:/CPU/CPU.srcs/sources_1/new/RFdatain.v
      D:/CPU/CPU.srcs/sources_1/new/registers.v
      D:/CPU/CPU.srcs/sources_1/new/PC.v
      D:/CPU/CPU.srcs/sources_1/new/NPC.v
      D:/CPU/CPU.srcs/sources_1/new/mem.v
      D:/CPU/CPU.srcs/sources_1/new/inst_decoder.v
      D:/CPU/CPU.srcs/sources_1/new/inst_count.v
      D:/CPU/CPU.srcs/sources_1/new/extend.v
      D:/CPU/CPU.srcs/sources_1/new/control.v
      D:/CPU/CPU.srcs/sources_1/new/alu.v
      D:/CPU/CPU.srcs/sources_1/new/show_choice.v
      D:/CPU/CPU.srcs/sources_1/new/cpu0228_09h06.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top cpu
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-8072-804-064/"
    if {$rt::useElabCache == false} {
      rt::run_rtlelab -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
