# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/CPU - 副本/CPU.cache/wt} [current_project]
set_property parent.project_path {D:/CPU - 副本/CPU.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {D:/CPU - 副本/CPU.srcs/sources_1/new/mux.v}
  {D:/CPU - 副本/CPU.srcs/sources_1/new/divider.v}
  {D:/CPU - 副本/CPU.srcs/sources_1/new/display.v}
  {D:/CPU - 副本/CPU.srcs/sources_1/new/Register.v}
  {D:/CPU - 副本/CPU.srcs/sources_1/new/Extender.v}
  {D:/CPU - 副本/CPU.srcs/sources_1/new/ram.v}
  {D:/CPU - 副本/CPU.srcs/sources_1/new/RFdatain.v}
  {D:/CPU - 副本/CPU.srcs/sources_1/new/registers.v}
  {D:/CPU - 副本/CPU.srcs/sources_1/new/PC.v}
  {D:/CPU - 副本/CPU.srcs/sources_1/new/NPC.v}
  {D:/CPU - 副本/CPU.srcs/sources_1/new/mem.v}
  {D:/CPU - 副本/CPU.srcs/sources_1/new/inst_decoder.v}
  {D:/CPU - 副本/CPU.srcs/sources_1/new/inst_count.v}
  {D:/CPU - 副本/CPU.srcs/sources_1/new/extend.v}
  {D:/CPU - 副本/CPU.srcs/sources_1/new/control.v}
  {D:/CPU - 副本/CPU.srcs/sources_1/new/alu.v}
  {D:/CPU - 副本/CPU.srcs/sources_1/new/show_choice.v}
  {D:/CPU - 副本/CPU.srcs/sources_1/new/cpu0228_09h06.v}
}
read_xdc {{D:/CPU - 副本/CPU.srcs/constrs_1/new/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{D:/CPU - 副本/CPU.srcs/constrs_1/new/Nexys4DDR_Master.xdc}}]

synth_design -top cpu -part xc7a100tcsg324-1
write_checkpoint -noxdef cpu.dcp
catch { report_utilization -file cpu_utilization_synth.rpt -pb cpu_utilization_synth.pb }
